name: Manual workflow
on:
  push:
    branches: [ main ]

jobs:
  manual:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      run: git clone https://github.com/hovhannesvrtanesyan/wordpress.git
    - name: Build image
      run: cd wordpress && docker build . -t ${{ secrets.DOCKER_HUB_LOGIN }}/${{ github.event.repository.name }}:${{ github.run_number }}
    - name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKER_HUB_LOGIN }} -p ${{ secrets.DOCKER_HUB_PASS }}
    - name: Push to DockerHub
      run: docker push ${{ secrets.DOCKER_HUB_LOGIN }}/${{ github.event.repository.name }}:${{ github.run_number }}
